language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install openssl; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libssl-dev libboost-dev autoconf automake autotools-dev libtool libltdl-dev && ./autogen.sh; fi

branches:
  only:
    - master
    - /^v\d+\./

script:
    - ./configure && make

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ec710ca767fdc82ba390
    on_success: change
    on_failure: always
    on_start: never

os:
  - osx
