language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev libssl-dev openssl libboost-dev autoconf automake autotools-dev libtool libltdl-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew link --force llvm; fi

branches:
  only:
    - master
    - /^v\d+\./

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ec710ca767fdc82ba390
    on_success: change
    on_failure: always
    on_start: never

os:
  - linux
